# cloudbuild-api.yaml
steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/$PROJECT_ID/philoagents-repo/philoagents-api:latest",
        ".",
      ]
    dir: "philoagents-api"

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/$PROJECT_ID/philoagents-repo/philoagents-api:latest",
      ]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "philoagents-api"
      - "--image"
      - "us-central1-docker.pkg.dev/$PROJECT_ID/philoagents-repo/philoagents-api:latest"
      - "--platform"
      - "managed"
      - "--region"
      - "us-central1"
      - "--allow-unauthenticated"
      - "--port"
      - "8000"
    secretEnv:
      - "GROQ_API_KEY"
      - "LANGSMITH_API_KEY"
      - "LANGSMITH_TRACING"
      - "LANGSMITH_ENDPOINT"
      - "LANGSMITH_PROJECT"
images:
  - "us-central1-docker.pkg.dev/$PROJECT_ID/philoagents-repo/philoagents-api:latest"
options:
  logging: CLOUD_LOGGING_ONLY
  availableSecrets:
    secrets:
      - secretManager:
          env: "GROQ_API_KEY"
          versionName: projects/$_PROJECT_NUMBER/secrets/GROQ_API_KEY/versions/latest
      - secretManager:
          env: "LANGSMITH_API_KEY"
          versionName: projects/$_PROJECT_NUMBER/secrets/LANGSMITH_API_KEY/versions/latest
      - secretManager:
          env: "LANGSMITH_TRACING"
          versionName: projects/$_PROJECT_NUMBER/secrets/LANGSMITH_TRACING/versions/latest
      - secretManager:
          env: "LANGSMITH_ENDPOINT"
          versionName: projects/$_PROJECT_NUMBER/secrets/LANGSMITH_ENDPOINT/versions/latest
      - secretManager:
          env: "LANGSMITH_PROJECT"
          versionName: projects/$_PROJECT_NUMBER/secrets/LANGSMITH_PROJECT/versions/latest
substitutions:
  _PROJECT_NUMBER: "635390037922" # Your Google Cloud Project Number
