# cloudbuild-ui.yaml
steps:
  # Build the Docker image for philoagents-ui
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/$PROJECT_ID/philoagents-repo/philoagents-ui:latest",
        ".",
      ]
    dir: "terresapan/business-model-canvas-agent/business-model-canvas-agent-533434f1b852a8f12c495db8aec75067e824a6a4/philoagents-ui"

  # Push the Docker image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/$PROJECT_ID/philoagents-repo/philoagents-ui:latest",
      ]

  # Deploy the image to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "philoagents-ui"
      - "--image"
      - "us-central1-docker.pkg.dev/$PROJECT_ID/philoagents-repo/philoagents-ui:latest"
      - "--platform"
      - "managed"
      - "--region"
      - "us-central1"
      - "--allow-unauthenticated"
      - "--port"
      - "8080"
images:
  - "us-central1-docker.pkg.dev/$PROJECT_ID/philoagents-repo/philoagents-ui:latest"
options:
  logging: CLOUD_LOGGING_ONLY
